services:
  - type: web
    name: aily-frontend
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: VITE_API_URL
        value: https://ai-student-r9ay.onrender.com
